services:
  mongodb:
    image: mongo:latest
    restart: always
    expose: 
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
  server:
    image: enemygg/nest:latest
    restart: always
    ports:
      - 80:3000
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=12345
      - SERVER_PORT=3000
      - DB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb
